
- name: Remove docker old version
  yum:
    name:
      - "docker"
      - "docker-client"
      - "docker-client-latest"
      - "docker-common"
      - "docker-latest"
      - "docker-latest-logrotate"
      - "docker-logrotate"
      - "docker-engine"
    state: absent

- name: Install yum-utils packages
  yum:
    name: yum-utils
    state: present

- name: Remove docker YUM repository
  yum_repository:
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    name: docker
    description: Docker YUM repository
    state: absent

- name: Add docker repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo   

- name: Install docker
  package:
    name: "{{item}}"
    state: present
  with_items: 
    - "docker-ce"
    - "docker-ce-cli"
    - "containerd.io"
    - "python3"
    - "python3-pip"
    - "python3-setuptools"
    - "virtualenv"

- name: Install docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-{{ansible_system}}-{{ansible_userspace_architecture}}
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'  

- name: Install docker module for python
  pip:
    name: docker