- name: Update apt cache
  apt: update_cache=yes
    
- name: Install required system packages
  apt: name={{item}} state=latest
    loop: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'python3-pip', 'python3-setuptools', 'virtualenv']

- name: Add Docker official GPG keys
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ansible_lsb}} stable
    state: present

- name: Update apt and install Docker
  apt: update_cache=yes name={{item}}
    loop: ['docker-ce', 'docker-ce-cli', 'containerd.io']

- name: Install Docker module for Python
   pip:
    name: docker

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-{{ansible_system}}-{{ansible_userspace_architecture}}
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'